{
    'name': 'Course',
    'author': 'Agisna',
    'version': '0.1',
    'depends': [
    ],
    'data': [
        'views/_menu_item.xml',
        'views/course_list.xml',
        'views/course_trainer.xml',
        'views/course_customer.xml',
        'views/course_order.xml',
        'views/sequence.xml',
        'template.xml',
        'print/course_order.xml',
        'print/course_order_complex.xml',
    ],
    'sequence': 3,
    'autoinstall': False,
    'installable': True,
    'application': True,
    'category': 'Academic',
    'summary': 'Course Management',
    'license': 'OPL-1',
    'website': 'https://github.com/agisna-bot',
    'description': 'ini latihan bikin course',
}